# Generated by Django 4.1.1 on 2022-10-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_date", models.CharField(max_length=100)),
                ("record_response", models.CharField(max_length=100)),
            ],
        ),
    ]
